apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: mysecret
spec:
  secretTemplates:
    - name: mysecret-sops
      labels:
        label1: value1
      annotations:
        key1: value1
      data:
        PG_PASSWORD: VG9Ub1RvVG8xMjMh
